-- =============================================================
-- Stage 1 工单：为 product 表的"分类 + 上架状态 + 价格区间"搜索加索引。
-- 这个文件会被 stage01 验收测试用 @Sql 自动执行（每次跑测试前）。
--
-- 【当前状态】下面全是注释 => 不创建任何索引 => EXPLAIN 走全表扫描(type=ALL) => 测试红。
-- 【你的任务】把索引建出来，让 EXPLAIN 命中(type=ref/range)，测试变绿。
--
-- 要求：索引名必须叫 idx_product_search（测试按这个名字判断幂等）。
-- 列的顺序需要你自己决定——想想：
--   * WHERE 里哪些是等值(=)、哪些是范围(BETWEEN)？
--   * ORDER BY 用的是哪一列？
--   * 最左前缀原则下，等值列、范围列、排序列应该怎么排？
--
-- 下面是一个"幂等添加索引"的模板（重复执行不会因 Duplicate key name 报错）。
-- 请把 (col_a, col_b, col_c) 换成你选择的真实列，然后【取消整段注释】：
--
-- SET @exist := (SELECT COUNT(1) FROM information_schema.statistics
--                WHERE table_schema = DATABASE()
--                  AND table_name   = 'product'
--                  AND index_name   = 'idx_product_search');
-- SET @ddl := IF(@exist = 0,
--                'ALTER TABLE product ADD INDEX idx_product_search (col_a, col_b, col_c)',
--                'DO 0');
-- PREPARE stmt FROM @ddl;
-- EXECUTE stmt;
-- DEALLOCATE PREPARE stmt;
-- =============================================================
